### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by bannanc** [vtlim/off-psi4#2]
I've noticed this is only python2 compatible right now. (Hopefully its just print statements that need to be changed). I'll try to get it updated to support both and make a PR.

**Comment by vtlim** [comment]
All the major scripts should actually be py3 compatible. The ones I use less often are not converted yet.

________________________________

**Comment by bannanc** [comment]
turns out it was just a couple of print statements :)

**Comment by bannanc** [comment]
[This line](https://github.com/vtlim/off-psi4/blob/master/filterConfs.py#L53): `testmol = next(Mol.GetConfs())` 
causes an error, I'm not sure if it is a python3 problem or not:

```

--------------------------------------------------------------------
TypeError                          Traceback (most recent call last)
<ipython-input-13-748fe10171fa> in <module>()
----> 1 next(mol.GetConfIter())

TypeError: 'OEConfIter' object is not an iterator

```

**Comment by vtlim** [comment]
@bannanc -- can you give me an example to reproduce the error? I used this script with python version 3.6.2 now and it ran okay on my set.

**Comment by bannanc** [comment]
@vtlim I don't know if it was a python version difference, or a version of openeye tools difference for some reason. I opened a pull request with the changes I made. PR #3 (I included the example I used and ran steps 1-6 from your README)

That error came from this line:
`testmol = next(Mol.GetConfs())`

I replaced it with this:
`testmol = Mol.GetConfs(oechem.OEHasConfIdx(0))`
and everything seemed to work, I think `GetConfs` is supposed to be an iterator so I don't know why it was causing an error.

**Comment by bannanc** [comment]
Oh, it just occurred to me you might be talking about everything working on python3, there are print statements in this repo missing parenthesis so if its working for you on python3 is it possible you have local changes you haven't put here?

**Comment by vtlim** [comment]
@bannanc - everything should be fine to close now?

**Comment by bannanc** [comment]
yep, I'll close
